# Generated by Django 4.0.4 on 2022-06-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_destination_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='team_name',
        ),
    ]
