# Generated by Django 4.0.4 on 2022-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_destination_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='price',
            new_name='Winnings',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
