# Generated by Django 4.0.4 on 2022-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_price_destination_winnings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_img', models.ImageField(upload_to='pics')),
                ('player_name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Destination',
            new_name='Teams',
        ),
    ]
