# Generated by Django 4.0.4 on 2022-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teammembers_teamname_alter_teammembers_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='player_img',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
