# Generated by Django 4.0.4 on 2022-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_teammembers_player_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoreupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=1000)),
                ('commentry', models.CharField(max_length=100000)),
            ],
        ),
    ]
