# Generated by Django 4.0.4 on 2022-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_scoreupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstteam', models.CharField(max_length=100000)),
                ('secondteam', models.CharField(max_length=100000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
