# Generated by Django 4.0.4 on 2022-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('Winnings', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('player_img', models.ImageField(upload_to='<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
