# Generated by Django 4.0.4 on 2022-06-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_team_delete_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_img',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='teamname',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.team', verbose_name='Link to product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='player_img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
