# Generated by Django 4.0.4 on 2022-06-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_team_player_img_remove_team_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.teammembers', verbose_name='Add Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Player_side',
            field=models.CharField(choices=[('Fast Bowler', 'Fast Bowler'), ('Spin Bowler', 'Spin Bowler'), ('Medium Pace Bowler', 'Medium Pace Bowler'), ('Batsmen', 'Batsmen'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], default='Right hand', max_length=20),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Player_type',
            field=models.CharField(choices=[('Fast Bowler', 'Fast Bowler'), ('Spin Bowler', 'Spin Bowler'), ('Medium Pace Bowler', 'Medium Pace Bowler'), ('Batsmen', 'Batsmen'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], default='All Rounder', max_length=20),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='teamin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='player_img',
            field=models.ImageField(upload_to=models.CharField(max_length=100)),
        ),
    ]
