# Generated by Django 4.0.4 on 2022-06-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_teammembers_team_team_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='teamin',
            new_name='teamname',
        ),
    ]
