# Generated by Django 4.0.4 on 2022-06-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_scoreupdate_player_type_scoreupdate_currentbat1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreupdate',
            old_name='Player_type',
            new_name='Balls_remaining',
        ),
    ]
