# Generated by Django 4.0.4 on 2022-06-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_player_type_scoreupdate_balls_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreupdate',
            name='team1',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='team2',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
