# Generated by Django 4.0.4 on 2022-06-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_scoreupdate_team1_scoreupdate_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Status',
            field=models.CharField(choices=[('Ongoing', 'ongoing'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='commentry',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='currentbat1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='currentbat2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='currentbowler',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='overs',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='score',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='wickets',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='Winnings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.teammember', verbose_name='Add Player'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
