# Generated by Django 4.0.4 on 2022-06-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_schedule_status_alter_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='Player_side',
            field=models.CharField(blank=True, choices=[('Right hand', 'Right hand'), ('Left hand', 'Left hand')], default='Right hand', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='Player_type',
            field=models.CharField(blank=True, choices=[('Fast Bowler', 'Fast Bowler'), ('Spin Bowler', 'Spin Bowler'), ('Medium Pace Bowler', 'Medium Pace Bowler'), ('Batsmen', 'Batsmen'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], default='All Rounder', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='teamname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
