# Generated by Django 4.0.4 on 2022-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_teammember_player_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreupdate',
            name='Balls_remaining',
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='currentbat1balls',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='currentbat1score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='currentbat2balls',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='currentbat2score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreupdate',
            name='totalovers',
            field=models.FloatField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='overs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreupdate',
            name='wickets',
            field=models.IntegerField(),
        ),
    ]
