# Generated by Django 4.0.4 on 2022-06-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_scoreupdate_balls_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreupdate',
            old_name='overs',
            new_name='over',
        ),
    ]
