# Generated by Django 4.0.4 on 2022-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_overs_scoreupdate_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreupdate',
            name='score',
            field=models.FloatField(),
        ),
    ]
